apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app-deployment
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: abhishekpande285/medicure-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
